spring:
  application:
    name: SpringRestQLExample
  jackson:
    serialization-inclusion: NON_EMPTY
server:
  port: 9090
project:
  group: core
  team: content
  application: 'SpringRestQLExample'
